[package]
name = "build-manifest"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.5.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.32"
flate2 = "1.0.26"
xz2 = "0.1.7"
tar = "0.4.38"
sha2 = "0.10.8"
rayon = "1.5.1"
hex = "0.4.3"
